export const mappings = {
  javascript: "javascript",
  js: "javascript",
  typescript: "typescript",
  ts: "typescript",
  python: "python",
  py: "python",
  java: "java",
  react: "react",
  reactjs: "react",
  nextjs: "nextjs",
  "next.js": "nextjs",
  nodejs: "nodejs",
  "node.js": "nodejs",
  angular: "angular",
  vue: "vuejs",
  vuejs: "vuejs",
  php: "php",
  go: "go",
  golang: "go",
  rust: "rust",
  swift: "swift",
  kotlin: "kotlin",
  flutter: "flutter",
  aws: "amazonwebservices",
  docker: "docker",
  kubernetes: "kubernetes",
  mongodb: "mongodb",
  mysql: "mysql",
  postgresql: "postgresql",
  postgres: "postgresql",
  redis: "redis",
  graphql: "graphql",
  html: "html5",
  css: "css3",
  tailwind: "tailwindcss",
  git: "git",
  github: "github",
  linux: "linux",
};

export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/google.png",
  "/microsoft.png",
  "/netflix.png",
];

export const feedbackSchema = {
  type: "object",
  properties: {
    totalScore: { type: "number" },
    categoryScores: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          score: { type: "number" },
          comment: { type: "string" },
        },
        required: ["name", "score", "comment"],
      },
    },
    strengths: { type: "array", items: { type: "string" } },
    areasForImprovement: { type: "array", items: { type: "string" } },
    finalAssessment: { type: "string" },
  },
  required: [
    "totalScore",
    "categoryScores",
    "strengths",
    "areasForImprovement",
    "finalAssessment",
  ],
};